### ISSUE TITLE
'FontAwesome' is not a system font and has not been loaded through Expo.Font.loadAsync 

### ISSUE THREAD

**Issue by fkbeys** [tarikpnr/react-native-ui-kit#4]
I m using Expo and getting this error.
i could not solve the issue. 

'FontAwesome' is not a system font and has not been loaded through Expo.Font.loadAsync

thank you for the amazing libriary...

**Comment by tarikfp** [comment]
This project uses [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) library under the hood. Thus, installing this library is required. 
Thank you for the issue though, just added a necessary note to README about this.
